---
abstract: 'Test framework for Config::Model'
author:
  - 'Dominique Dumont'
build_requires:
  Module::Build: '0.34'
configure_requires:
  Module::Build: '0.34'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Model-Tester
requires:
  File::Copy::Recursive: '0'
  Getopt::Long: '0'
  Log::Log4perl: '1.11'
  Path::Tiny: '0'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::File::Contents: '0'
  Test::Log::Log4perl: '0'
  Test::Memory::Cycle: '0'
  Test::More: '0'
  Test::Warn: '0'
  perl: '5.012'
resources:
  bugtracker: https://github.com/dod38fr/config-model-tester/issues
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model-tester.git
version: '4.007'
x_generated_by_perl: v5.32.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: LGPL-2.1
